#!/bin/bash
# Single source of truth for kickmsg build options.

declare -A OPT_DEFAULTS=(
    [unit_tests]=OFF
    [benchmarks]=OFF
    [examples]=OFF
    [tsan]=OFF
)

declare -A OPT_DESCRIPTIONS=(
    [unit_tests]="Build unit tests"
    [benchmarks]="Build benchmarks (requires Google Benchmark)"
    [examples]="Build examples"
    [tsan]="Enable ThreadSanitizer"
)

declare -A OPT_CMAKE_FLAGS=(
    [unit_tests]="BUILD_UNIT_TESTS"
    [benchmarks]="BUILD_BENCHMARKS"
    [examples]="BUILD_EXAMPLES"
    [tsan]="ENABLE_TSAN"
)

# Only options that gate a Conan dependency
declare -A OPT_CONAN_FLAGS=(
    [unit_tests]="unit_tests"
    [benchmarks]="benchmarks"
)

# Load .buildconfig into the CONFIG associative array.
load_buildconfig() {
    declare -gA CONFIG
    for key in "${!OPT_DEFAULTS[@]}"; do
        CONFIG[$key]="${OPT_DEFAULTS[$key]}"
    done

    if [ -f "$CONFIG_FILE" ]; then
        while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            if [[ -v "OPT_DEFAULTS[$key]" ]]; then
                CONFIG[$key]="$value"
            else
                warn "Unknown option in $CONFIG_FILE: $key (ignored)"
            fi
        done < "$CONFIG_FILE"
    fi
}

save_buildconfig() {
    {
        echo "# kickmsg build configuration"
        echo "# Generated by scripts/configure.sh"
        for key in $(echo "${!CONFIG[@]}" | tr ' ' '\n' | sort); do
            echo "$key=${CONFIG[$key]}"
        done
    } > "$CONFIG_FILE"
}

show_buildconfig() {
    if [ ! -f "$CONFIG_FILE" ]; then
        info "No .buildconfig found, showing defaults:"
    else
        info "Current configuration ($CONFIG_FILE):"
    fi
    for key in $(echo "${!CONFIG[@]}" | tr ' ' '\n' | sort); do
        printf "  %-20s %s\n" "$key" "${CONFIG[$key]}"
    done
}
