#!/bin/bash
# Single source of truth for kickmsg build options.
#
# Uses parallel arrays (not associative arrays / `declare -A`) so the
# script works on macOS's system bash 3.2 — associative arrays are a
# bash 4+ feature, and macOS ships 3.2 for GPL-licensing reasons.  Each
# option occupies the same index across all OPT_* arrays.

OPT_NAMES=(        unit_tests                    benchmarks                                      examples        tsan                      )
OPT_DEFAULTS=(     OFF                           OFF                                             OFF             OFF                       )
OPT_DESCRIPTIONS=( "Build unit tests"            "Build benchmarks (requires Google Benchmark)"  "Build examples" "Enable ThreadSanitizer" )
OPT_CMAKE_FLAGS=(  BUILD_UNIT_TESTS              BUILD_BENCHMARKS                                BUILD_EXAMPLES  ENABLE_TSAN               )

# Conan flags: only options that actually gate a Conan-provided dep.
# Empty slot = option has no Conan side effect.
OPT_CONAN_FLAGS=(  unit_tests                    benchmarks                                      ""              ""                        )

# CONFIG_VALUES is a parallel array keyed by the same index as OPT_NAMES.
# Callers never index it directly — use config_get / config_set.
CONFIG_VALUES=()

# Return the index of $1 in OPT_NAMES, or empty if not present.
opt_index() {
    local name="$1" i
    for i in "${!OPT_NAMES[@]}"; do
        if [[ "${OPT_NAMES[$i]}" == "$name" ]]; then
            echo "$i"
            return 0
        fi
    done
    return 1
}

opt_is_known() { opt_index "$1" >/dev/null; }

opt_default()     { local i; i=$(opt_index "$1") && echo "${OPT_DEFAULTS[$i]}"; }
opt_description() { local i; i=$(opt_index "$1") && echo "${OPT_DESCRIPTIONS[$i]}"; }
opt_cmake_flag()  { local i; i=$(opt_index "$1") && echo "${OPT_CMAKE_FLAGS[$i]}"; }
opt_conan_flag()  { local i; i=$(opt_index "$1") && echo "${OPT_CONAN_FLAGS[$i]}"; }

config_init() {
    CONFIG_VALUES=()
    local d
    for d in "${OPT_DEFAULTS[@]}"; do
        CONFIG_VALUES+=("$d")
    done
}

config_get() { local i; i=$(opt_index "$1") && echo "${CONFIG_VALUES[$i]}"; }

config_set() {
    local i
    i=$(opt_index "$1") || return 1
    CONFIG_VALUES[$i]="$2"
}

# Load .buildconfig into CONFIG_VALUES.  Unknown keys are warned-and-ignored.
load_buildconfig() {
    config_init
    if [ -f "$CONFIG_FILE" ]; then
        local key value
        while IFS='=' read -r key value; do
            [[ -z "$key" || "$key" == \#* ]] && continue
            key=$(echo "$key" | xargs)
            value=$(echo "$value" | xargs)
            if opt_is_known "$key"; then
                config_set "$key" "$value"
            else
                warn "Unknown option in $CONFIG_FILE: $key (ignored)"
            fi
        done < "$CONFIG_FILE"
    fi
}

save_buildconfig() {
    {
        echo "# kickmsg build configuration"
        echo "# Generated by scripts/configure.sh"
        local name
        for name in "${OPT_NAMES[@]}"; do
            echo "$name=$(config_get "$name")"
        done
    } > "$CONFIG_FILE"
}

show_buildconfig() {
    if [ ! -f "$CONFIG_FILE" ]; then
        info "No .buildconfig found, showing defaults:"
    else
        info "Current configuration ($CONFIG_FILE):"
    fi
    local name
    for name in "${OPT_NAMES[@]}"; do
        printf "  %-20s %s\n" "$name" "$(config_get "$name")"
    done
}
