#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

source "$SCRIPT_DIR/lib/log.sh"
source "$SCRIPT_DIR/lib/build_options.sh"

usage() {
    cat <<EOF
Usage: $0 <build_dir> [OPTIONS]

Set up the build environment: detect (or select) a compiler, generate a Conan
profile and a CMake toolchain file, install dependencies via Conan, and
configure CMake.

Build options are read from .buildconfig (generated by scripts/configure.sh).
If no .buildconfig exists, defaults are used.

Arguments:
  build_dir                 Output directory for generated files (required)

Options:
  --target <os-arch>        Cross-compile for the given platform instead of
                            building natively. Supported targets:
                              linux-aarch64   ARM64 Linux (RPi3/4/5, Rockchip, …)
  --build-type <type>       CMake build type: Release (default) or Debug
  -h, --help                Show this help message and exit

Examples:
  $0 build                             # native Release build
  $0 build --build-type Debug          # native Debug build
  $0 build --target linux-aarch64      # cross-compile for ARM64 Linux

  scripts/configure.sh build --with=unit_tests
  $0 build
EOF
}

build_dir=""
CROSS_TARGET=""
BUILD_TYPE="Release"

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --target)
            CROSS_TARGET="$2"
            shift 2
            ;;
        --build-type)
            BUILD_TYPE="$2"
            shift 2
            ;;
        *)
            if [ -z "$build_dir" ]; then
                build_dir="$1"
            else
                error "Unknown argument: $1"
                usage
                exit 1
            fi
            shift
            ;;
    esac
done

if [ -z "$build_dir" ]; then
    usage
    exit 1
fi

# Check conan
MIN_CONAN_VERSION="2.10.0"

step "Checking prerequisites"
if ! command -v conan >/dev/null 2>&1; then
    error "Conan is not installed. Install with: pip install conan"
    exit 1
fi

INSTALLED_CONAN_VERSION=$(conan --version | awk '{print $3}')

if [[ "$(printf '%s\n' "$MIN_CONAN_VERSION" "$INSTALLED_CONAN_VERSION" | sort -V | head -n1)" != "$MIN_CONAN_VERSION" ]]; then
    error "Conan version $MIN_CONAN_VERSION or higher is required (found $INSTALLED_CONAN_VERSION)"
    exit 1
fi
success "Conan $INSTALLED_CONAN_VERSION"

mkdir -p "$build_dir"
info "Build directory: $build_dir"

CONFIG_FILE="$build_dir/.buildconfig"

# Read .buildconfig
load_buildconfig

if [ -f "$CONFIG_FILE" ]; then
    step "Reading build configuration"
    for key in "${OPT_NAMES[@]}"; do
        info "  $key = $(config_get "$key")"
    done
else
    info "No .buildconfig found, using defaults (run scripts/configure.sh to customize)"
fi

# Map .buildconfig values to Conan -o flags / CMake -D flags.
to_conan_bool() { [[ "$1" == "ON" ]] && echo "True" || echo "False"; }

CONAN_OPTIONS=""
CMAKE_OPTIONS=""
for key in "${OPT_NAMES[@]}"; do
    value=$(config_get "$key")
    cmake_flag=$(opt_cmake_flag "$key")
    conan_flag=$(opt_conan_flag "$key")
    [ -n "$cmake_flag" ] && CMAKE_OPTIONS+=" -D${cmake_flag}=${value}"
    [ -n "$conan_flag" ] && CONAN_OPTIONS+=" -o &:${conan_flag}=$(to_conan_bool "$value")"
done

# Compiler detection & profile generation
TEMPLATE_CMAKE_TOOLCHAIN="$PROJECT_DIR/cmake/toolchain.cmake.template"
OUTPUT_CMAKE_TOOLCHAIN="$build_dir/toolchain.cmake"
TEMPLATE_CONAN_PROFILE="$PROJECT_DIR/conan/profile.txt.template"
OUTPUT_CONAN_PROFILE="$build_dir/profile.txt"

if [ -n "$CROSS_TARGET" ]; then
    step "Cross-compilation setup (target: $CROSS_TARGET)"

    case "$CROSS_TARGET" in
        linux-aarch64)
            CROSS_CC="aarch64-linux-gnu-gcc"
            CROSS_CXX="aarch64-linux-gnu-g++"
            ARCH_NAME="armv8"
            SYSTEM_PROCESSOR="aarch64"
            OS_NAME="Linux"
            SYSTEM_NAME="Linux"
            COMPILER_NAME="gcc"
            LIBCXX_NAME="libstdc++11"
            CROSS_ARCH_FLAGS="-march=armv8-a -mtune=generic"
            ;;
        *)
            error "Unsupported cross-compilation target: $CROSS_TARGET"
            info "Supported targets: linux-aarch64"
            exit 1
            ;;
    esac

    if ! command -v "$CROSS_CC" >/dev/null 2>&1; then
        error "Cross-compiler $CROSS_CC not found. Install with:"
        info "  sudo apt install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu"
        exit 1
    fi

    CROSS_VERSION_FULL=$("$CROSS_CC" -dumpfullversion -dumpversion 2>/dev/null)
    IFS='.' read -r major minor patch <<< "$CROSS_VERSION_FULL"
    CROSS_VERSION="$major.$minor"

    success "Cross-compiler: $CROSS_CC ($CROSS_VERSION_FULL)"

    source "$PROJECT_DIR/tools/setup/detect_compiler.sh"

    OUTPUT_BUILD_PROFILE="$build_dir/profile_build.txt"
    sed \
      -e "s|@OS_NAME@|Linux|g" \
      -e "s|@ARCH_NAME@|x86_64|g" \
      -e "s|@COMPILER_NAME@|gcc|g" \
      -e "s|@LIBCXX_NAME@|libstdc++11|g" \
      -e "s|@MAJOR_VERSION@|${GREATEST_VERSION}|g" \
      -e "s|@BINARY_PATH_CC@|$(command -v $GREATEST_CC)|g" \
      -e "s|@BINARY_PATH_CXX@|$(command -v $GREATEST_CXX)|g" \
      "$TEMPLATE_CONAN_PROFILE" > "$OUTPUT_BUILD_PROFILE"

    sed \
      -e "s|@OS_NAME@|${OS_NAME}|g" \
      -e "s|@ARCH_NAME@|${ARCH_NAME}|g" \
      -e "s|@COMPILER_NAME@|${COMPILER_NAME}|g" \
      -e "s|@LIBCXX_NAME@|${LIBCXX_NAME}|g" \
      -e "s|@MAJOR_VERSION@|${CROSS_VERSION}|g" \
      -e "s|@BINARY_PATH_CC@|$(command -v $CROSS_CC)|g" \
      -e "s|@BINARY_PATH_CXX@|$(command -v $CROSS_CXX)|g" \
      "$TEMPLATE_CONAN_PROFILE" > "$OUTPUT_CONAN_PROFILE"

    sed \
      -e "s|@SYSTEM_NAME@|${SYSTEM_NAME}|g" \
      -e "s|@BINARY_PATH_CC@|$(command -v $CROSS_CC)|g" \
      -e "s|@BINARY_PATH_CXX@|$(command -v $CROSS_CXX)|g" \
      -e "s|@ARCH_FLAGS@|${CROSS_ARCH_FLAGS}|g" \
      "$TEMPLATE_CMAKE_TOOLCHAIN" > "$OUTPUT_CMAKE_TOOLCHAIN"

    cat >> "$OUTPUT_CMAKE_TOOLCHAIN" <<CROSS_EOF
set(CMAKE_SYSTEM_PROCESSOR ${SYSTEM_PROCESSOR})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
CROSS_EOF

    CONAN_PROFILE_ARGS="-pr:h $OUTPUT_CONAN_PROFILE -pr:b $OUTPUT_BUILD_PROFILE"

else
    # ── Native build ────────────────────────────────────────────────────
    step "Detecting native compiler"
    source "$PROJECT_DIR/tools/setup/detect_compiler.sh"

    conan profile detect --force > /dev/null 2>&1
    ARCH_NAME=$(conan profile show -cx host | grep "arch=" | cut -d'=' -f2)

    info "Architecture for Conan: $ARCH_NAME"

    OS=$(uname -s)
    if [[ "$OS" == "Darwin" ]]; then
        OS_NAME="Macos"
        COMPILER_NAME="apple-clang"
        LIBCXX_NAME="libc++"
        SYSTEM_NAME="Darwin"
        ARCH_NAME="armv8\|x86_64"
    else
        OS_NAME="Linux"
        COMPILER_NAME="gcc"
        LIBCXX_NAME="libstdc++11"
        SYSTEM_NAME="Linux"
    fi

    ARCH_FLAGS=""

    sed \
      -e "s|@SYSTEM_NAME@|${SYSTEM_NAME}|g" \
      -e "s|@BINARY_PATH_CC@|$(command -v $GREATEST_CC)|g" \
      -e "s|@BINARY_PATH_CXX@|$(command -v $GREATEST_CXX)|g" \
      -e "s|@ARCH_FLAGS@|${ARCH_FLAGS}|g" \
      "$TEMPLATE_CMAKE_TOOLCHAIN" > "$OUTPUT_CMAKE_TOOLCHAIN"

    sed \
      -e "s|@OS_NAME@|${OS_NAME}|g" \
      -e "s|@ARCH_NAME@|${ARCH_NAME}|g" \
      -e "s|@COMPILER_NAME@|${COMPILER_NAME}|g" \
      -e "s|@LIBCXX_NAME@|${LIBCXX_NAME}|g" \
      -e "s|@MAJOR_VERSION@|${GREATEST_VERSION}|g" \
      -e "s|@BINARY_PATH_CC@|$(command -v $GREATEST_CC)|g" \
      -e "s|@BINARY_PATH_CXX@|$(command -v $GREATEST_CXX)|g" \
      "$TEMPLATE_CONAN_PROFILE" > "$OUTPUT_CONAN_PROFILE"

    if [[ "$OS" == "Darwin" ]]; then
        echo "OSX_ARCH_VARIANTS=x86_64;arm64" >> "$OUTPUT_CONAN_PROFILE"

        echo "" >> "$OUTPUT_CONAN_PROFILE"
        echo "[platform_tool_requires]" >> "$OUTPUT_CONAN_PROFILE"
        
    fi
    cat "$OUTPUT_CONAN_PROFILE"

    CONAN_PROFILE_ARGS="-pr $OUTPUT_CONAN_PROFILE -pr:b $OUTPUT_CONAN_PROFILE"
fi

# Conan install
step "Installing Conan dependencies"
info "Installing $BUILD_TYPE dependencies..."
conan install "$PROJECT_DIR/conanfile.py" -of="$build_dir" $CONAN_PROFILE_ARGS $CONAN_OPTIONS --build=missing -s build_type=$BUILD_TYPE

# CMake configure
step "Configuring CMake ($BUILD_TYPE)"
cmake -S "$PROJECT_DIR" -B "$build_dir" \
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
    -DCMAKE_TOOLCHAIN_FILE="$OUTPUT_CMAKE_TOOLCHAIN" \
    $CMAKE_OPTIONS

success "Build environment ready in $build_dir"
info "Next step: cd $build_dir && make -j"
